# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 2m
  tests: false
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
#    - deadcode
    - goconst
    - goimports
    - gosimple
#    - govet
    - ineffassign
    - misspell
    # - staticcheck
    - unconvert
    # - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude:
    - "`testTopic` is unused"
    - "`errTimeout` is unused"
    - "`blockPeriod` is unused"

  exclude-rules:
    - path: src/blockchain/smilobft/crypto/blake2b/
      linters:
        - deadcode
    - path: src/blockchain/smilobft/crypto/bn256/cloudflare
      linters:
        - deadcode
    - path: src/blockchain/smilobft/p2p/discv5/
      linters:
        - deadcode
    - path: src/blockchain/smilobft/core/vm/instructions_test.go
      linters:
        - goconst